pipeline:
  style_check: 
    image: python:3.9-buster
#    when:
#      event: pull_request
    commands:
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt
      - python -m pip install pylint flake8 mypy>=0.971
      - python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - mypy --strict ./
      - python -m pylint -f parseable ./*.py 
      
  unit_tests:
    image: python:${TAG}-buster
#    when:
#      event: pull_request
    commands:
      - ls
      - python -m venv venv 
      - /bin/bash -c "source venv/bin/activate"
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt
      - pytest tests/
    secrets: [ amazfit_email, amazfit_password ]

matrix:
  TAG:
    - 3.8
    - 3.9
    - 3.10
    - 3.11
